export type EngineFactSheet = {
  id: string;
  historicalName: string;
  accuracy: "documented" | "fictional-proxy" | "documented-inspiration";
  builder: string;
  builtYear: number;
  className: string;
  service: "mixed" | "passenger" | "freight";
  wheelArrangement: string;
  driverDiameterInches: number;
  leadingWheelDiameterInches: number;
  trailingWheelDiameterInches: number;
  engineAndTenderTons: number;
  tractiveEffortLbf: number;
  maximumSpeedMph: number;
  fuelType: "coal" | "oil";
  fuelCapacity: number;
  fuelCapacityUnit: "lb" | "gal";
  fuelCapacityLabel: string;
  waterCapacityGallons: number;
  status: string;
  summary: string;
  sourceUrl: string;
};

export const ENGINE_FACT_SHEETS: Readonly<Record<string, EngineFactSheet>> = Object.freeze({
  "tom-thumb": { id:"tom-thumb", historicalName:"Ironbound No. 1", accuracy:"fictional-proxy", builder:"Ironbound Railway Shops", builtYear:1908, className:"Ten-Wheeler", service:"mixed", wheelArrangement:"4-6-0", driverDiameterInches:63, leadingWheelDiameterInches:33, trailingWheelDiameterInches:0, engineAndTenderTons:126, tractiveEffortLbf:26000, maximumSpeedMph:55, fuelType:"coal", fuelCapacity:18000, fuelCapacityUnit:"lb", fuelCapacityLabel:"18,000 lb coal", waterCapacityGallons:7000, status:"Fictional Ironbound roster", summary:"A light mixed-traffic Ten-Wheeler. Values are design targets grounded in period practice, not historical claims.", sourceUrl:"https://www.victorianrailways.net/motive%20power/d_steam/dsteam.html" },
  "southern-4501": { id:"southern-4501", historicalName:"Southern Railway No. 4501", accuracy:"documented", builder:"Baldwin Locomotive Works", builtYear:1911, className:"Ms Mikado", service:"freight", wheelArrangement:"2-8-2", driverDiameterInches:63, leadingWheelDiameterInches:33, trailingWheelDiameterInches:43, engineAndTenderTons:270, tractiveEffortLbf:53900, maximumSpeedMph:60, fuelType:"coal", fuelCapacity:24000, fuelCapacityUnit:"lb", fuelCapacityLabel:"24,000 lb coal", waterCapacityGallons:8000, status:"Operational", summary:"A Southern freight Mikado preserved and operated by the Tennessee Valley Railroad Museum.", sourceUrl:"https://www.tvrail.com/equipment/southern-4501/" },
  "prr-1361": { id:"prr-1361", historicalName:"PRR K4s No. 1361", accuracy:"documented", builder:"PRR Juniata Shops", builtYear:1918, className:"K4s Pacific", service:"passenger", wheelArrangement:"4-6-2", driverDiameterInches:80, leadingWheelDiameterInches:36, trailingWheelDiameterInches:50, engineAndTenderTons:259, tractiveEffortLbf:44460, maximumSpeedMph:90, fuelType:"coal", fuelCapacity:44000, fuelCapacityUnit:"lb", fuelCapacityLabel:"44,000 lb coal", waterCapacityGallons:13475, status:"Under restoration", summary:"A high-driver passenger Pacific known as the Spirit of Altoona.", sourceUrl:"https://www.railroadcity.org/k4-1361-history" },
  "nkp-765": { id:"nkp-765", historicalName:"Nickel Plate Road No. 765", accuracy:"documented", builder:"Lima Locomotive Works", builtYear:1944, className:"S-2 Berkshire", service:"mixed", wheelArrangement:"2-8-4", driverDiameterInches:69, leadingWheelDiameterInches:36, trailingWheelDiameterInches:43, engineAndTenderTons:401, tractiveEffortLbf:64135, maximumSpeedMph:80, fuelType:"coal", fuelCapacity:44000, fuelCapacityUnit:"lb", fuelCapacityLabel:"44,000 lb coal", waterCapacityGallons:22000, status:"Operational", summary:"A Lima Berkshire built for fast freight and now active in excursion service.", sourceUrl:"https://fortwaynerailroad.org/nickel-plate-road-no-765/" },
  "atsf-3751": { id:"atsf-3751", historicalName:"Santa Fe No. 3751", accuracy:"documented", builder:"Baldwin Locomotive Works", builtYear:1927, className:"3751 Northern", service:"passenger", wheelArrangement:"4-8-4", driverDiameterInches:80, leadingWheelDiameterInches:36, trailingWheelDiameterInches:44, engineAndTenderTons:437, tractiveEffortLbf:71719, maximumSpeedMph:103, fuelType:"oil", fuelCapacity:7101, fuelCapacityUnit:"gal", fuelCapacityLabel:"7,101 US gal oil", waterCapacityGallons:20000, status:"Operational", summary:"Santa Fe's first 4-8-4, rebuilt with 80-inch drivers and converted from coal to oil.", sourceUrl:"https://www.sbrhs.org/equipment/santa-fe-3751/specifications.html" },
  "nw-611": { id:"nw-611", historicalName:"Norfolk & Western No. 611", accuracy:"documented", builder:"N&W Roanoke Shops", builtYear:1950, className:"J", service:"passenger", wheelArrangement:"4-8-4", driverDiameterInches:70, leadingWheelDiameterInches:36, trailingWheelDiameterInches:42, engineAndTenderTons:436, tractiveEffortLbf:84981, maximumSpeedMph:110, fuelType:"coal", fuelCapacity:70000, fuelCapacityUnit:"lb", fuelCapacityLabel:"70,000 lb coal", waterCapacityGallons:20000, status:"Operational", summary:"A streamlined coal-burning passenger locomotive built in Roanoke for high-speed service.", sourceUrl:"https://www.dhr.virginia.gov/historic-registers/128-6479/" },
  "up-844": { id:"up-844", historicalName:"Union Pacific No. 844", accuracy:"documented", builder:"American Locomotive Company", builtYear:1944, className:"FEF-3 Northern", service:"passenger", wheelArrangement:"4-8-4", driverDiameterInches:80, leadingWheelDiameterInches:36, trailingWheelDiameterInches:42, engineAndTenderTons:454, tractiveEffortLbf:63450, maximumSpeedMph:120, fuelType:"oil", fuelCapacity:6200, fuelCapacityUnit:"gal", fuelCapacityLabel:"6,200 US gal oil", waterCapacityGallons:23500, status:"Operational; never retired", summary:"Union Pacific's last steam locomotive, built for high-speed service and later converted to oil.", sourceUrl:"https://www.up.com/about-us/history/steam/living-legend-844" },
  "nw-1218": { id:"nw-1218", historicalName:"Norfolk & Western No. 1218", accuracy:"documented", builder:"N&W Roanoke Shops", builtYear:1943, className:"A", service:"freight", wheelArrangement:"2-6-6-4", driverDiameterInches:70, leadingWheelDiameterInches:33, trailingWheelDiameterInches:42, engineAndTenderTons:573, tractiveEffortLbf:114000, maximumSpeedMph:70, fuelType:"coal", fuelCapacity:60000, fuelCapacityUnit:"lb", fuelCapacityLabel:"60,000 lb coal", waterCapacityGallons:22000, status:"Static display", summary:"A fast articulated freight locomotive preserved in Roanoke, Virginia.", sourceUrl:"https://www.dhr.virginia.gov/historic-registers/128-6655/" },
  "challenger-3985": { id:"challenger-3985", historicalName:"Union Pacific Challenger No. 3985", accuracy:"documented", builder:"American Locomotive Company", builtYear:1943, className:"4664-4 Challenger", service:"mixed", wheelArrangement:"4-6-6-4", driverDiameterInches:69, leadingWheelDiameterInches:36, trailingWheelDiameterInches:45, engineAndTenderTons:537, tractiveEffortLbf:97350, maximumSpeedMph:70, fuelType:"oil", fuelCapacity:6450, fuelCapacityUnit:"gal", fuelCapacityLabel:"6,450 US gal oil", waterCapacityGallons:25000, status:"Under restoration", summary:"An articulated locomotive designed to move fast freight over western grades.", sourceUrl:"https://rrhma.com/loc3985/" },
  "big-boy-4014": { id:"big-boy-4014", historicalName:"Union Pacific Big Boy No. 4014", accuracy:"documented", builder:"American Locomotive Company", builtYear:1941, className:"4884-1 Big Boy", service:"freight", wheelArrangement:"4-8-8-4", driverDiameterInches:68, leadingWheelDiameterInches:36, trailingWheelDiameterInches:42, engineAndTenderTons:595, tractiveEffortLbf:135375, maximumSpeedMph:80, fuelType:"oil", fuelCapacity:6000, fuelCapacityUnit:"gal", fuelCapacityLabel:"6,000 US gal No. 5 oil", waterCapacityGallons:25000, status:"Operational", summary:"A 1.2-million-pound articulated freight locomotive restored by Union Pacific and converted to oil; it originally carried 56,000 lb of coal.", sourceUrl:"https://www.up.com/about-us/history/steam/big-boy-4014" },
  "the-flyer-1907": { id:"the-flyer-1907", historicalName:"The Flyer No. 222", accuracy:"fictional-proxy", builder:"Ironbound Heritage Works", builtYear:1907, className:"Atlantic", service:"passenger", wheelArrangement:"4-4-2", driverDiameterInches:80, leadingWheelDiameterInches:36, trailingWheelDiameterInches:48, engineAndTenderTons:238, tractiveEffortLbf:32000, maximumSpeedMph:75, fuelType:"coal", fuelCapacity:26000, fuelCapacityUnit:"lb", fuelCapacityLabel:"26,000 lb coal", waterCapacityGallons:11000, status:"Fictional Ironbound roster", summary:"A fictional high-driver Atlantic grounded in period 4-4-2 passenger practice.", sourceUrl:"https://www.rrpicturearchives.net/showPicture.aspx?id=5422017" },
  "polar-express-1225": { id:"polar-express-1225", historicalName:"Pere Marquette No. 1225", accuracy:"documented-inspiration", builder:"Lima Locomotive Works", builtYear:1941, className:"N-1 Berkshire", service:"mixed", wheelArrangement:"2-8-4", driverDiameterInches:69, leadingWheelDiameterInches:33, trailingWheelDiameterInches:43, engineAndTenderTons:401, tractiveEffortLbf:69350, maximumSpeedMph:70, fuelType:"coal", fuelCapacity:44000, fuelCapacityUnit:"lb", fuelCapacityLabel:"44,000 lb coal", waterCapacityGallons:22000, status:"Operational", summary:"The real Pere Marquette 1225 is the mechanical and visual origin; film artwork is not copied.", sourceUrl:"https://michigansteamtrain.com/equipment/" }
});

export const engineFactSheetFor = (engineId: string) => ENGINE_FACT_SHEETS[engineId] ?? ENGINE_FACT_SHEETS["tom-thumb"];

export function wheelAxleCounts(wheelArrangement: string) {
  if (!/^\d+(?:-\d+){2,}$/.test(wheelArrangement)) throw new Error(`Invalid Whyte arrangement: ${wheelArrangement}`);
  const groups = wheelArrangement.split("-").map(Number);
  if (groups.length < 3 || groups.some((value) => !Number.isInteger(value) || value < 0 || value % 2)) throw new Error(`Invalid Whyte arrangement: ${wheelArrangement}`);
  return { leading: groups[0] / 2, drivers: groups.slice(1, -1).reduce((sum, wheels) => sum + wheels / 2, 0), driverGroups: groups.length - 2, trailing: groups.at(-1)! / 2 };
}
